//
//  MessagesViewController.swift
//  NowPlayingMessageExtension
//
//  Created by Thomas Greenwood on 9/6/18.
//  Copyright © 2018 Thomas Greenwood. All rights reserved.
//

import UIKit
import Messages
import MediaPlayer

class MessagesViewController: MSMessagesAppViewController {
	override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
	
	@IBAction func shareAlbumPressed(_ sender: Any) {
		composeMessage(isSharingAlbum: true)
	
	}
	@IBAction func shareButtonPressed(_ sender: Any) {
		composeMessage(isSharingAlbum: false)
	}
	
	private func composeMessage(isSharingAlbum: Bool) {
		let song = Music.getNowPlayingInfo()
		
		let conversation = activeConversation
		let session = conversation?.selectedMessage?.session ?? MSSession()
		
		let layout = MSMessageTemplateLayout()
		layout.image = song.artwork
		layout.imageTitle =  (isSharingAlbum == true) ? "Now Playing Album:" : "Now Playing Song:"
        layout.caption = (isSharingAlbum == true) ? song.albumTitle : song.title
		layout.subcaption = song.artist
		
		let message = MSMessage(session: session)
		message.layout = layout
		message.summaryText = "Shared Now Playing"
		
		conversation?.insert(message)
	}

    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
		
        // Use this method to configure the extension and restore previously stored state.
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dissmises the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }

}
